export const FETCH_FLAVORS = 'FETCH_FLAVORS';
export const FETCH_SIZES = 'FETCH_SIZES';
export const FETCH_INCREMENTS = 'FETCH_INCREMENTS';
export const SELECT_FLAVOR = 'SELECT_FLAVOR';
export const SELECT_SIZE = 'SELECT_SIZE';
export const SELECT_INCREMENTS = 'SELECT_INCREMENTS';
